/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Board = IDL.Variant({
  'StateBoard' : IDL.Null,
  'CBSE' : IDL.Null,
  'ICSE' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'studentName' : IDL.Text,
  'timestamp' : Time,
  'contactNumber' : IDL.Text,
  'board' : Board,
  'parentName' : IDL.Text,
  'standard' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
  'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitEnquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Board, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Board = IDL.Variant({
    'StateBoard' : IDL.Null,
    'CBSE' : IDL.Null,
    'ICSE' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'studentName' : IDL.Text,
    'timestamp' : Time,
    'contactNumber' : IDL.Text,
    'board' : Board,
    'parentName' : IDL.Text,
    'standard' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllEnquiries' : IDL.Func([], [IDL.Vec(Enquiry)], ['query']),
    'getEnquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitEnquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Board, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };